SparqlForHumans.Server/Controllers/LuceneController.cs
using Microsoft.AspNetCore.Mvc;
using SparqlForHumans.Core.Services;

namespace SparqlForHumans.Server.Controllers
{
    [Produces("application/json")]
    [Route("api/Lucene")]
    public class LuceneController : Controller
    {
        public IActionResult Autocomplete(string term)
        {
            var filteredItems = QueryService.QueryByLabel(term);

            return Json(filteredItems);
        }
    }
}

SparqlForHumans.Server/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SparqlForHumans.Server.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

SparqlForHumans.Server/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<h1>AutoComplete</h1>
Search on the Lucene Index
<p />
<div>
    <label>Search: </label>
    <input type="text" id="LuceneAutocomplete" data-autocomplete="@Url.Action("Autocomplete","Lucene")" autocomplete="on" />
    <br /><br /><br />
    <label>Selected Item:</label>
    <h2 id="txtLabel"></h2>
    <h2 id="txtType"></h2>
    <h3 id="txtDescription"></h3>
    <br />
    <ul id="txtProperties"></ul>
</div>

<script>
    $(document).ready(function () {
        $("#LuceneAutocomplete").each(function () {
            $(this).autocomplete({
                //DataSource
                source: $(this).attr("data-autocomplete"),
                minLength: 2,
                delay: 200,

                //Description Tooltip
                focus: function (event, ui) {
                    $(".ui-autocomplete > li").attr("title", ui.item.description);
                },

                //OnSelect
                select: function (event, ui) {
                    console.log(ui.item);
                    $('#txtLabel').text("Label: " + ui.item.label);
                    $('#txtType').text("Type: " + ui.item.typeLabel + " (" + ui.item.type + ")");
                    $('#txtDescription').text("Description: " + ui.item.description);
                    $.each(ui.item.properties, function (index, value) {
                        $('#txtProperties').append("<li>" + value.item2 + " (" + value.item1 + ")</li>");
                    });
                    return false;
                }
            }).autocomplete("instance")._renderItem = function (ul, item) {
                return $("<li>")
                    .append("<div>" + item.label + " (" + item.typeLabel + ") </div>")
                    .appendTo(ul);
            };;
        });
    });
</script>

SparqlForHumans.Server/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SparQL For Humans</title>
    <script src="http://code.jquery.com/jquery-3.3.1.js" ></script>
    <script src="http://code.jquery.com/ui/1.12.1/jquery-ui.js" ></script>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">SparQL For Humans</a>
            </div>
            @*<div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                </ul>
            </div>*@
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    <environment include="Development">
        @*<script src="~/lib/jquery/dist/jquery.js"></script>*@
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>